### ISSUE TITLE
Import App Fails in DNN 9.2 with 2sxc 9.23

### ISSUE THREAD

**Issue by Accuraty** [2sic/app-mobius-forms#12]
Tried importing 2sxcApp_Forms_01.04.01.zip in to a clean, new DNN 9.02.00 install with 2sxc 9.23. The import failed, see attached. If this app is not currently compatible with the new versions of DNN/2sxc, should I expect that it would be fixed some time soon?
 
![image](https://user-images.githubusercontent.com/653301/39552950-1a7c254e-4e31-11e8-99af-ae85b572ba65.png)
 
Looking through DNN's Event log/viewer, there were a slew of errors with messages like:
General Exception, Message: something went wrong - can't find type in app, but it's not a global type, so I must cancel
General Exception, Message:too many or to few content types found for the content-type @All - found 0
Admin Alert, 
2sxc-Api:Auto-Log Exception
ModuleId:420
2sModC(24)CB.Mod(e7):parent#420, content-block#420, z#2, a#0
2sModC(24)CB.Mod(e7)Sxc.Instnc(fe):get SxcInstance for a:0 cb:420
2sModC(24)CB.Mod(e7)DS.Create(95):will create view data source
2sModC(24)CB.Mod(e7)Sxc.Instnc(fe)App.PermCk(b4):init for type:, itm: (), meta1: , meta2:
2sModC(24)CB.Mod(e7)DS.Create(95):mid#420, draft:True, template:
2sModC(24)CB.Mod(e7)DS.Factry(e8):get init #2/0, draft:True, config:False
2sModC(24)CB.Mod(e7)DS.Create(95):use pipeline upstream:True
2sModC(24)CB.Mod(e7)DS.Create(95):no template override
2sModC(24)CB.Mod(e7)Sxc.Instnc(fe)CG.RefMan(2d):get selectable apps
2sModC(24)CB.Mod(e7)Sxc.Instnc(fe)CG.RefMan(2d)App:zone base for z#2

**Comment by iJungleboy** [comment]
this is most likely an issue with the latest 2sxc - and should be fixed in 9.30 (to be released tomorrow)

**Comment by Accuraty** [comment]
I noticed 9.30 has some kind of native/core Forms available now. Does that replace this Forms app or will there still be a new version of 2sxcApp_Forms_01.0x.xx.zip that will work with DNN 9.2 and 2sxc 9.23 and higher? I did install 9.30 and the import still fails hard and made 2sxc unusable without manually deleting files and folders and settings.

**Comment by iJungleboy** [comment]
No, there are many scenarios requiring completely custom forms. We'll release Mobius 2 - probably tomorrow - with new file-upload features :)
